[fix] Fixing Required Environment Variables
clusterctl 0.3.9 and 0.3.10

```
Error: value for variables [OPENSTACK_SSH_AUTHORIZED_KEY] is not set.
Please set the value using os environment variables or the clusterctl
config file
```

This is my first CNCF pull request.
Please point out any mistakes.