vendoring: pin structured-merge-diff to v4.4.1
A backward incompatible change was made:
https://github.com/kubernetes-sigs/structured-merge-diff/commit/c68c9ee5bc5f9b73b5785e38a6a28a6c5b654572

Which is not compatible with k8s v0.31.2.
An update was done very recently but not released yet:
https://github.com/kubernetes/kubernetes/commit/2bc17d1cf03f2f2bcd683e7e79f01c929951cca3#diff-1966d58e97bf87f3cd69e4957a2c948a72ca97c36df3ea099ac0ea6592e42dbfL56

So in the meantime we need to pin structured-merge-diff to v4.4.1 to not
have this compilation error:

```
/root/go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/managedfields/internal/structuredmerge.go:56:4: unknown field IgnoredFields in struct literal of type merge.Updater
/root/go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/managedfields/internal/structuredmerge.go:73:4: unknown field IgnoredFields in struct literal of type merge.Updater
```